wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.27
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
    t:
      1:
      - 1
      2:
      - 1
      4: 3.6.9
      5: 0.10.27
      8:
      - 5
recog_model:
  desc: null
  value: weights/recog/eager-vortex/crnn_192_64.pth16
upsample:
  desc: null
  value:
  - LR
  - cor_upconv
  - cor_upsamp
  - cor_upsamp_nn
  - origin
